spring:
  data:
    mongodb:
      uri: mongodb+srv://yuop1022:1234@cluster0.ucslnmx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

